import os
import nbformat
from nbclient import NotebookClient
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import io
import base64

# Path to your notebook
notebook_path = "pi_plus/SIDIS_Copper.ipynb"  # <-- change this

# Output PDF path
output_pdf = "Copper_SIDIS_.pi+.pdf"


# Check if file exists and is non-empty
if not os.path.isfile(notebook_path) or os.path.getsize(notebook_path) == 0:
    raise FileNotFoundError(f"Notebook not found or empty: {notebook_path}")

# Load notebook
try:
    with open(notebook_path, 'r', encoding='utf-8') as f:
        nb = nbformat.read(f, as_version=4)
except Exception as e:
    raise ValueError(f"Failed to read notebook {notebook_path}: {e}")

# Execute notebook
client = NotebookClient(nb)
client.execute()

# Extract all plots from outputs
images = []

for cell in nb.cells:
    if cell.cell_type != "code":
        continue
    for output in cell.get("outputs", []):
        # Only consider display_data or execute_result outputs
        if output.output_type in ["display_data", "execute_result"]:
            data = output.get("data", {})
            png_base64 = data.get("image/png")
            if png_base64:
                images.append(base64.b64decode(png_base64))

# Save images to a single PDF
if not images:
    print("No figures were generated by this notebook.")
else:
    with PdfPages(output_pdf) as pdf:
        for img_bytes in images:
            img = plt.imread(io.BytesIO(img_bytes))
            fig, ax = plt.subplots(figsize=(16, 12))
            ax.imshow(img)
            ax.axis("off")
            pdf.savefig(fig)
            plt.close(fig)

    print(f"Saved {len(images)} figure(s) to {output_pdf}")
